In [1]:
# Import Environment Dependencies
import tweepy
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
from config import api_key, api_key_secret, access_token,access_token_secret
from pprint import pprint
from datetime import date
from datetime import timedelta
from config import gkey
import requests
import urllib
from urllib.request import urlopen
import json
import gmaps

In [2]:
# Get Authentication and API Handle from Tweepy

auth = tweepy.OAuthHandler(consumer_key=api_key, consumer_secret=api_key_secret)

auth.set_access_token(access_token,access_token_secret)

api = tweepy.API(auth)

In [33]:
# function to display data of each tweet
def printtweetdata(n, ith_tweet):
    print()
    print(f"Tweet {n}:")
    print(f"Username:{ith_tweet[0]}")
    print(f"Description:{ith_tweet[1]}")
    print(f"Location:{ith_tweet[2]}")
    print(f"Following Count:{ith_tweet[3]}")
    print(f"Follower Count:{ith_tweet[4]}")
    print(f"Total Tweets:{ith_tweet[5]}")
    print(f"Retweet Count:{ith_tweet[6]}")
    print(f"Tweet Text:{ith_tweet[7]}")
    print(f"Hashtags Used:{ith_tweet[8]}")
    
    
 # function to perform data extraction
# scrape(words, location, date_since)
def scrape(words):
      
# Creating DataFrame using pandas
    db = pd.DataFrame(columns=['username', 'description', 'location', 'following',
                               'followers', 'totaltweets', 'retweetcount', 'text', 'hashtags'])
   
   
 # Creating a Cursor using the .Cursor() method to search through twitter for the required tweets.
    
    tweets = tweepy.Cursor(api.search_tweets,q=words, lang="en", 
             tweet_mode='extended').items(100)
    
   
    list_tweets = [tweet for tweet in tweets]
      
    
    
      
    # we will iterate over each tweet in the list for extracting information about each tweet
    i = 1  
    for tweet in list_tweets:
        
        username = tweet.user.screen_name
        description = tweet.user.description
        location = tweet.user.location
        following = tweet.user.friends_count
        followers = tweet.user.followers_count
        totaltweets = tweet.user.statuses_count
        retweetcount = tweet.retweet_count
        hashtags = tweet.entities['hashtags']
        
        # Retweets can be distinguished by a retweeted_status attribute,
        # in case it is an invalid reference, except block will be executed
        try:
            text = tweet.retweeted_status.full_text
        except AttributeError:
            text = tweet.full_text
        hashtext = list()
        for j in range(0, len(hashtags)):
            hashtext.append(hashtags[j]['text'])
          
        # Here we are appending all the extracted information in the DataFrame
        ith_tweet = [username, description, location, following,
                     followers, totaltweets, retweetcount, text, hashtext]
        db.loc[len(db)] = ith_tweet
          
        # Function call to print tweet data on screen
        #printtweetdata(i, ith_tweet)
        i = i+1
    return db
        
        
    
#     filename = 'scraped_tweets.csv'
      
    # Saving the resultset as a CSV file.
#     db.to_csv(filename)

if __name__ == '__main__':
         
# Enter Hashtag and initial date
    print("Enter Keyword to search for")
    words = input()
#     print("Enter Date since The Tweets are required in yyyy-mm--dd")
#     date_since = input()
#     print("Enter Location of Tweets are required")
#     location = input()

#     words='cricket'
#     date_since='2021-10-18'
#     location='Atlanta'
#     db=scrape(words, location, date_since)
  
    db=scrape(words)
#     print(db)

Enter Keyword to search for
iowa

In [34]:
# db.head()
db_df = pd.DataFrame(db)
db_df
# --------------
no_blnk_local_df = db_df.loc[((db_df['location'] !="") & (db_df["retweetcount"] > 0)),:].sort_values('retweetcount',ascending=False).head(50)
no_blnk_local_df

,username,description,location,following,followers,totaltweets,retweetcount,text,hashtags
2,BlueDrum2,Socialist‚Ä¶EVERYTHING is ENVIRONMENTAL~I seek t...,ALSO @Lesleyjassüëàüèæüåé,1365,915,52630,152,Just *one day* after a UAW member was killed w...,[]
55,AmberForIowa,ü•õüçûüêà - Radical Love & Righteous Fights. #BlackL...,"Ankeny, IA",3243,8445,25751,57,ICYMI: The Meskwaki Nation is calling on 66 Io...,[]
32,justiceseeker78,üîú #CNP #Koch #Mercer /üîö : üåé. ‚Äî #FederalistSoci...,United States,2733,821,7180,57,ICYMI: The Meskwaki Nation is calling on 66 Io...,[]
61,AmishScientist,"I like books, birds, socks & loud music. I'm d...","Tucson, AZ",5003,1967,103448,54,What short story collection prizes would you s...,[]
95,nutxaq,White dude in the PNW coming at you live from ...,Way over on the left.,2425,1620,63788,41,Imagine if @ewarren would have dropped out aft...,[]
10,cwillott,#WomenForBernie2020 #WithTheseMittens Changing...,"California, USA",987,1797,84977,41,Imagine if @ewarren would have dropped out aft...,[]
83,occupytheport,OccupythePort: The Original Port Shutdown Twit...,West Coast,4396,4174,248470,41,Imagine if @ewarren would have dropped out aft...,[]
85,peacepumpkinpic,"Indie screenwriter, director, producer. Projec...","Toronto, Canada",1836,2125,182025,41,Imagine if @ewarren would have dropped out aft...,[]
64,pjmugs,,Pennsylvania,260,312,256612,30,‚ÄúMcAuliffe spends big in final days on sanctio...,[]
27,TrainspottingRT,you like sharing your #Railways pics? tag your...,"Wien, √ñsterreich",2465,12747,17165,23,A brief history of the Minneapolis &amp; St. L...,[]
75,meredit71840781,masks hide lip lines üíõüíõüíõüêùüêù üíâüíâKamala is my VP ...,Iowa,1473,534,84002,12,.@PatGrassley and the @IAHouseGOP voting to ex...,[]
44,Graham_Fried,C/O 2022 - Urbandale IA - WR/DB/KR - 6‚Äô2 185 -...,"Urbandale, IA",225,369,132,9,After a great call with @Coach_Niemann I am ex...,[GoHawks]
41,WattierJack,Urbandale Safety - Iowa - 6‚Äô1‚Äô - 190 - Class o...,"Urbandale, IA",251,356,206,9,After a great call with @Coach_Niemann I am ex...,[]
39,GreysonElse,Urbandale 2022 DE/FB 6‚Äô2 220 (515) 240-3137 Fo...,Urbandale IA,302,123,84,9,After a great call with @Coach_Niemann I am ex...,[]
36,ParkerStewart_2,Urbandale C/O ‚Äò22,"Urbandale, IA",51,66,18,9,After a great call with @Coach_Niemann I am ex...,[]
42,Kai_Black23,3‚≠êÔ∏è WR/TE | Urbandale high school 2023 |4.00 G...,"Urbandale, IA",287,639,110,9,After a great call with @Coach_Niemann I am ex...,[]
29,KaseyRoss01,"Urbandale C/O 2022 6‚Äô2, 2x State qualifier, Fr...","Urbandale, IA",228,149,256,9,After a great call with @Coach_Niemann I am ex...,[]
24,thebrickwahl87,Dir. of Scouting @PrepRedzoneDAK | Midwest Sen...,"Minnesota, USA",2539,3958,12382,9,After a great call with @Coach_Niemann I am ex...,[]
13,PrepRedzoneIA,The comprehensive authority for High School fo...,"Iowa, USA",2312,3316,15149,9,After a great call with @Coach_Niemann I am ex...,[]
21,Friedrichs1Matt,,"Iowa, USA",45,35,354,9,After a great call with @Coach_Niemann I am ex...,[]
15,BigGameWC,Helping young athletes achieve their dreams an...,"Iowa City, IA",660,1107,972,6,We are excited to announce that Eva Diaz has c...,[]
71,Iowa_Recruiting,Iowa students passionate about the Hawkeyes. S...,"Iowa City, IA",488,10286,58735,6,The latest big board from @nfldraftscout just ...,[]
6,smiley2814,I‚Äôm just living my life one memory at a time. ...,"Dallas, TX",280,68,3533,6,Republicans will win all 4 Iowa districts in 2...,[]
58,tcj,Working husband and father; believes in a more...,"Washington, DC",2514,1168,89413,6,I've been wondering about this myself! Judge ...,[]
33,PrepRedzoneIA,The comprehensive authority for High School fo...,"Iowa, USA",2312,3316,15149,6,Iowa City West freshman quarterback Jack Walla...,[]
51,gk7713,,United States,206,60,8654,5,My statement on Iowa‚Äôs new congressional maps:...,[]
16,sarg_sunshine,grandma to 3 great kids and mom to a recued da...,United States,3189,1966,157294,4,"Thrilled that we had a fair, nonpartisan redis...",[]
25,iowa_edm,Official Twitter for the Iowa EDM student orga...,Iowa City,112,29,41,3,"We have recently been asked for ""scripts"" for ...",[]
4,GossettJoey,Assistant Principal at Delta High School,Delta High School in Muncie IN,219,314,6781,3,5Ô∏è‚É£ Delta High School wrestlers are competing ...,[]
26,rpmcintyre16,@WVUhoops Video Coordinator / Class of 2016 #L...,"Morgantown, WV",608,682,5413,2,Check out this year's Gold Mini-Pack featuring...,[]
22,Captain_Jack58,"Christian, Husband, Proud Girl-Dad, Girl-Grand...","Kansas, USA",609,127,2044,2,Looking for a new role? Join RailWorks as a Tr...,[]
23,Meidas_Sammi,Ex-GOP turned proud Dem. Politics junkie and k...,"DSM, IA",8139,7862,44496,2,This was an inevitable and bullshit narrative ...,[]
69,WVUhoops,The official Twitter account of West Virginia ...,"Morgantown, WV",99,328087,15226,2,Check out this year's Gold Mini-Pack featuring...,[]
81,gazettedotcom,100% independent and employee-owned. \nKeep up...,"Cedar Rapids, Iowa",3015,54525,78076,2,"Jeff Johnson, K.J. Pilcher and Nathan Ford pre...",[]
74,MatthewIA03,Biden won. Trump lost.,Iowa citizen,1814,1508,46053,2,This was an inevitable and bullshit narrative ...,[]
84,coach_wendell,"Father, Husband, Teacher, Wrestling Coach, ACC...","Charlottesville, Virginia",965,778,8560,1,Another Iowa commit for @uvawrestling this tim...,[]
82,MightyFeklhr,"Hawkeye football, pro-wrestling, and rock and ...",Beta Quadrant (home),2807,1288,116544,1,Iowa is home to the world's only active riding...,[]
1,codygoodwin,I cover wrestling and high school sports for t...,IOWA via KCMO,278,10805,37685,1,Another Iowa commit for @uvawrestling this tim...,[]
59,WBBDaily,Celebrating the Women's Game Since 2005üèÄ #Grow...,Ann Arbor,37,7166,64784,1,"For Iowa women's basketball team, success hing...",[]
53,amcneer,National Sales Assistant at WNDU-TV,"Granger, IN",5001,1856,622806,1,"For Iowa women's basketball team, success hing...",[]
47,PWCGOP,Official Twitter Account for the Republican Co...,"Prince William, VA",3391,2194,5129,1,McAuliffe spends big in final days on sanction...,[FoxNews]
43,5bulletbob,,"West Chester, Ohio",548,64,2306,1,Your Iowa fun fact of the day! \n\n#Iowa #Base...,"[Iowa, Baseball, FieldofDreams, Travel]"
31,PrepRedzoneIA,The comprehensive authority for High School fo...,"Iowa, USA",2312,3316,15149,1,Tough loss but great matchup vs #1 ranked WR i...,[]
96,uiowa,Official University of Iowa account. With more...,"Iowa City, IA",684,122801,20992,1,Iowa is home to the world's only active riding...,[]

In [35]:
loc_lat= []
loc_long = []
loc_name=[]

for location in no_blnk_local_df['location']:
    location_url = f"https://maps.googleapis.com/maps/api/geocode/json?address={location}&key={gkey}"
    geo_data = requests.get(location_url).json()
    
    try:
        loc_lat.append(geo_data["results"][0]["geometry"]["location"]["lat"])
        loc_long.append(geo_data["results"][0]["geometry"]["location"]["lng"])
        loc_name.append(location)
    except IndexError:
        print("Index Out of Range")
        pass
    
# print(loc_lat)
# print(loc_long)
# print(loc_name)

Index Out of Range
Index Out of Range
Index Out of Range

In [36]:
data_df = {'location' :loc_name, 'latitude': loc_lat, 'longitude':loc_long}
location_df = pd.DataFrame(data_df)
location_df

                          location   latitude   longitude
0                       Ankeny, IA  41.731788  -93.600128
1                    United States  37.090240  -95.712891
2                       Tucson, AZ  32.222607 -110.974711
3                  California, USA  36.778261 -119.417932
4                       West Coast  62.411363 -149.072971
5                  Toronto, Canada  43.653226  -79.383184
6                     Pennsylvania  41.203322  -77.194525
7                 Wien, √ñsterreich  48.208174   16.373819
8                             Iowa  41.878003  -93.097702
9                    Urbandale, IA  41.629398  -93.760741
10                   Urbandale, IA  41.629398  -93.760741
11                    Urbandale IA  41.629398  -93.760741
12                   Urbandale, IA  41.629398  -93.760741
13                   Urbandale, IA  41.629398  -93.760741
14                   Urbandale, IA  41.629398  -93.760741
15                  Minnesota, USA  46.729553  -94.685900
16                       Iowa, USA  41.878003  -93.097702
17                       Iowa, USA  41.878003  -93.097702
18                   Iowa City, IA  41.661128  -91.530168
19                   Iowa City, IA  41.661128  -91.530168
20                      Dallas, TX  32.776664  -96.796988
21                  Washington, DC  38.907192  -77.036871
22                       Iowa, USA  41.878003  -93.097702
23                   United States  37.090240  -95.712891
24                   United States  37.090240  -95.712891
25                       Iowa City  41.661128  -91.530168
26  Delta High School in Muncie IN  40.278276  -85.348072
27                  Morgantown, WV  39.629526  -79.955897
28                     Kansas, USA  39.011902  -98.484246
29                         DSM, IA  41.586835  -93.624959
30                  Morgantown, WV  39.629526  -79.955897
31              Cedar Rapids, Iowa  41.977880  -91.665623
32                    Iowa citizen  42.520753  -93.263940
33       Charlottesville, Virginia  38.029306  -78.476678
34                   IOWA via KCMO  39.102630  -94.583407
35                       Ann Arbor  42.280826  -83.743038
36                     Granger, IN  41.753382  -86.110838
37              Prince William, VA  38.783894  -77.607787
38              West Chester, Ohio  39.332126  -84.417267
39                       Iowa, USA  41.878003  -93.097702
40                   Iowa City, IA  41.661128  -91.530168

In [37]:
grp_retweet = no_blnk_local_df.groupby(["location"])
# print(grp_retweet)
retweet_count = grp_retweet["retweetcount"].sum()
# print(retweet_count)
retweet_df = pd.DataFrame({"retweetcount":retweet_count}).sort_values('retweetcount',ascending=False)
retweet_df

                                retweetcount
location
ALSO @Lesleyjassüëàüèæüåé                      152
United States                             66
Ankeny, IA                                57
Tucson, AZ                                54
Urbandale, IA                             45
West Coast                                41
Way over on the left.                     41
California, USA                           41
Toronto, Canada                           41
Pennsylvania                              30
Iowa, USA                                 25
Wien, √ñsterreich                          23
Iowa City, IA                             13
Iowa                                      12
Minnesota, USA                             9
Urbandale IA                               9
Dallas, TX                                 6
Washington, DC                             6
Morgantown, WV                             4
Delta High School in Muncie IN             3
Iowa City                                  3
Kansas, USA                                2
Iowa citizen                               2
DSM, IA                                    2
Cedar Rapids, Iowa                         2
Beta Quadrant (home)                       1
Ann Arbor                                  1
West Chester, Ohio                         1
IOWA via KCMO                              1
Charlottesville, Virginia                  1
Granger, IN                                1
Prince William, VA                         1

In [38]:
merge_retweet_df = pd.merge(location_df,retweet_df, on="location",how="left")
merge_retweet_df = merge_retweet_df.drop_duplicates()
merge_retweet_df

                          location   latitude   longitude  retweetcount
0                       Ankeny, IA  41.731788  -93.600128            57
1                    United States  37.090240  -95.712891            66
2                       Tucson, AZ  32.222607 -110.974711            54
3                  California, USA  36.778261 -119.417932            41
4                       West Coast  62.411363 -149.072971            41
5                  Toronto, Canada  43.653226  -79.383184            41
6                     Pennsylvania  41.203322  -77.194525            30
7                 Wien, √ñsterreich  48.208174   16.373819            23
8                             Iowa  41.878003  -93.097702            12
9                    Urbandale, IA  41.629398  -93.760741            45
11                    Urbandale IA  41.629398  -93.760741             9
15                  Minnesota, USA  46.729553  -94.685900             9
16                       Iowa, USA  41.878003  -93.097702            25
18                   Iowa City, IA  41.661128  -91.530168            13
20                      Dallas, TX  32.776664  -96.796988             6
21                  Washington, DC  38.907192  -77.036871             6
25                       Iowa City  41.661128  -91.530168             3
26  Delta High School in Muncie IN  40.278276  -85.348072             3
27                  Morgantown, WV  39.629526  -79.955897             4
28                     Kansas, USA  39.011902  -98.484246             2
29                         DSM, IA  41.586835  -93.624959             2
31              Cedar Rapids, Iowa  41.977880  -91.665623             2
32                    Iowa citizen  42.520753  -93.263940             2
33       Charlottesville, Virginia  38.029306  -78.476678             1
34                   IOWA via KCMO  39.102630  -94.583407             1
35                       Ann Arbor  42.280826  -83.743038             1
36                     Granger, IN  41.753382  -86.110838             1
37              Prince William, VA  38.783894  -77.607787             1
38              West Chester, Ohio  39.332126  -84.417267             1

In [40]:
# data_df = {'Latitude': loc_lat, 'Longitude':loc_long}
# coord_df = pd.DataFrame(data_df)

coord = merge_retweet_df[["latitude","longitude"]]
popularity = merge_retweet_df["retweetcount"].astype(float)
# print(coord)
# print(popularity)

In [41]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(coord, weights=popularity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig1 = gmaps.figure(layout=figure_layout)

In [10]:
# Assign the marker layer to a variable
markers = gmaps.marker_layer(coord)

# Add the layer to the map
fig1.add_layer(markers)
fig1

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi‚Ä¶